### ISSUE TITLE
Request to update to google lighthouse 5.1.0 version

### ISSUE THREAD

**Issue by nraddy** [femtopixel/docker-google-lighthouse#10]
Thank you for maintaining this docker. Could you please upgrade lighthouse version to "v5.1.0" which has fix for "NO_FCP" error?

I am running into this error as described here:
https://github.com/GoogleChrome/lighthouse/issues/7534
which is fixed in latest version of lighthouse.

Thank you!

**Comment by jaymoulin** [comment]
Fixed my autobuilder - should be fixed with https://github.com/femtopixel/docker-google-lighthouse/commit/a7f23f1f4acd274155e27c915d63726eb4d3b723

**Comment by nraddy** [comment]
fantastic, thank you!
