### ISSUE TITLE
Unable to connect to Chrome - No such file or directory libgbm.so.1

### ISSUE THREAD

**Issue by b2013767** [femtopixel/docker-google-lighthouse#16]
**Description**

I am receiving the following when running the latest image on macOS v10.14.5. 

**Command line I used to start the container**

`docker run --rm --cap-add=SYS_ADMIN --name "lighthouse" -t -v "$(pwd)/lighthouse-reports/:/home/chrome/reports" "femtopixel/google-lighthouse:latest" "http://www.google.com"`

**Steps to reproduce the issue:**
1. Run the docker run command above
2. Recieve the below error

**Describe the results you received:**
`ChromeLauncher Waiting for browser....................................................................................................... +503ms
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:45353 +3ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.io8VYLM/chrome-err.log +0ms
  ChromeLauncher:error /usr/bin/chromium-browser: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
  ChromeLauncher:error  +1ms
Unable to connect to Chrome`

**Describe the results you expected:**
Lighthouse to run successfully. The below was gained by running the following command 
`docker run --rm --cap-add=SYS_ADMIN --name "lighthouse" -t -v "$(pwd)/lighthouse-reports/:/home/chrome/reports" "femtopixel/google-lighthouse:v5.5.0" "http://www.google.com"`

  `status Generating results... +0ms
  Printer html output written to /home/chrome/reports/_2020-03-02_10-49-22.report.html +130ms
  CLI Protip: Run lighthouse with `--view` to immediately open the HTML report in your browser +1ms
  ChromeLauncher Killing Chrome instance 21 +1ms`

**Additional information you deem important (e.g. issue happens only occasionally):**
It seemed to be working last week when we were using the latest version. Just began having issues today

**Comment by jaymoulin** [comment]
Thank you for reporting this. If you find this product useful, please consider donation to help me continue maintain and create great products ([![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin))

**Comment by dburrows** [comment]
Getting this error too,  I've pulled the latest digest from docker: 
`sha256:801f73049224c761d66e01269bc40758fd87994e7be0663af294ae9d55f81292`
and still getting  the error

**Comment by jaymoulin** [comment]
Thank @dburrows for your support, this is very appreciated!
