### ISSUE TITLE
Bump to lighthouse version 6.2

### ISSUE THREAD

**Issue by yovizzle** [femtopixel/docker-google-lighthouse#20]
hey there, when I run `docker run --rm -it femtopixel/google-lighthouse lighthouse --version` I get 5.60. Is it possible to get it bumped to lighthouse 6.2? The new tests are good. Thanks!

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

The actual latest version is 6.3. You can download it by typing this command : `docker pull femtopixel/google-lighthouse`
