### ISSUE TITLE
The reports

### ISSUE THREAD

**Issue by eghos** [femtopixel/docker-google-lighthouse#3]
Hiya,

I am new to this. I run that command and I don't see any reports in there apart from the folder. Could you point me in the right direction?

**Comment by jaymoulin** [comment]
What command did you run? you should mount a volume to `/home/chrome/reports` to get your reports generated to the specified folder. `/path/to/your/report` must be a valid path where you want your reports generated

**Comment by eghos** [comment]
Hi Jaymoulin, thanks for getting back . Yes I ran the command and get the error message 

Runtime error encountered: EACCES: permission denied, open '/home/chrome/reports/<website_url>._2018-07-16_14-54-36.report.html'
Error: EACCES: permission denied, open '/home/chrome/reports/<website_url>._2018-07-16_14-54-36.report.html'. 

Apparently there is permission issue inside the container.

Please help

**Comment by eghos** [comment]
Hi Jaymoulin ,

I found the answer here : https://hub.docker.com/r/femtopixel/google-lighthouse-puppeteer/

All good now. Thanks for your response.
