### ISSUE TITLE
filtering the report

### ISSUE THREAD

**Issue by eghos** [femtopixel/docker-google-lighthouse#4]
Hi 
I know this is not the appropriate place to ask for this help but it will be very much appreciated if you are able to help.

Basically, this docker implementation is really beautiful . I have implemented it and it works in my pipeline and writes the report to a json file . However because of how big the file is, splunk is not able to index the entire lines of the file. Is there a way to run the lighthouse command such that the output it filtered..meaning to specify the components of the report that we need e.g SEO, Performance . I know this is possible in the browser but not sure about the command line. Thanks for your help

**Comment by jaymoulin** [comment]
You can change some configuration by passing parameters after your site URL (https://github.com/GoogleChrome/lighthouse#cli-options).

You can also create your own configuration file using this syntax : https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md

and adding it with a similar command to
```
docker run --rm --name lighthouse -it -v /path/to/your/report:/home/chrome/reports -v $PWD/config.js:/config/config.js --cap-add=SYS_ADMIN femtopixel/google-lighthouse <your_site_url> --config-path=/config/config.js
```
