### ISSUE TITLE
Runtime error encountered: The environment variable CHROME_PATH

### ISSUE THREAD

**Issue by phpchap** [femtopixel/docker-google-lighthouse#5]
I get the following error when running the latest container, rolling back to v.3.0.3 fixes the issue

Runtime error encountered: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.

**Comment by jaymoulin** [comment]
This is really strange since the chrome version didn't changed since many version on this project. This may have impact on several other images as well 
- https://github.com/femtopixel/docker-google-lighthouse-puppeteer
- https://github.com/femtopixel/docker-google-chrome-headless

**Comment by jaymoulin** [comment]
Related to https://github.com/femtopixel/docker-google-chrome-headless/commit/eb95ab7e7d16f948968abc25cc4e1c9076076e9c
