### ISSUE TITLE
Error response from daemon: OCI runtime create failed: container_linux.go:348...

### ISSUE THREAD

**Issue by yippeykeiyay** [femtopixel/docker-google-lighthouse#6]
**Description**

When running a Lighthouse test I receive the following error. It appears to be tied to the version of Docker we have installed - we have two servers, and the newer one running a newer version is the one with the problem. The other works every time.

```
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/home/chrome/reports\") set in config.json failed: permission denied": unknown.
```

**Command line I used to start the container**
```
docker run --rm --name lighthouse -v /tmp/bc4151e9-8132-4b2e-bf8c-27133749fc53/:/home/chrome/reports --cap-add=SYS_ADMIN femtopixel/google-lighthouse:4.0.0-alpha.0-amd64 'https://www.example.com/' --quiet --max-wait-for-load=30000 --output=html --output=json --output=csv --output-path=/home/chrome/reports/www_example_com --emulated-form-factor=desktop --throttling-method=provided
```

**Steps to reproduce the issue:**
1. Install `Docker version 18.09.0, build 4d60db4`
2. Use the above command to run a Lighthouse test on any website.

**Describe the results you received:**
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/home/chrome/reports\") set in config.json failed: permission denied": unknown.
```

**Describe the results you expected:**
A test to run and then I can view the output files in the desired director.

**Additional information you deem important (e.g. issue happens only occasionally):**
We have two Ubuntu 16.04 servers running Lighthouse tests - only one of them has this issue. It's running `Docker version 18.09.0, build 4d60db4`.

**Provide some logs (`docker logs lighthouse`)**
No logs available due to `--rm` option killing the container (`Error: No such container: lighthouse`). When `--rm` is removed there's still no logs.

**Output of `docker inspect lighthouse --format='{{index .Config.Labels.version}}'`:**

```
4.0.0-alpha.0-amd64
```

**Comment by jaymoulin** [comment]
Humm. I can see several things that may cause this issue. 

First: It's docker related, therefore I won't be able to help you and this issue should be reported on the moby repo.
Second: It's a simple right error that could be fixed with a `chmod o+wx /tmp/bc4151e9-8132-4b2e-bf8c-27133749fc53`

Hope this'll help

**Comment by yippeykeiyay** [comment]
Hi @jaymoulin, thank you for your reply.

I'd already tried the `chmod` command but it didn't work unfortunately. The directory that the error message references is `/home/chrome/reports` which is internal to this Docker image AFAIK, which is why I don't think the `/tmp` permissions worked and why I thought it might be an issue with this repo.

**Comment by jaymoulin** [comment]
You mount your `/tmp` to a volume to `/home/chrome/reports`. Docker need the right to write to that specific folder even if its a container so the right issue is still valid (just look at the readme, it's a FAQ ;))

**Comment by yippeykeiyay** [comment]
I originally tried the `chmod` command from the repo's README when I first encountered the problem, before opening this issue. Also, I've had the `EACCES` before when trying to mount different directories, so have fixed the permissions problem before with that command.

Thank you for the info, I'll keep digging.

**Comment by jaymoulin** [comment]
Still sticking to my position.

```bash
[jay:~] $ mkdir tmp
[jay:~] $ chmod 0 tmp/
[jay:~] $ docker run --rm --name lighthouse -v "$PWD/tmp/:/home/chrome/reports" --cap-add=SYS_ADMIN femtopixel/google-lighthouse:4.0.0-alpha.0-amd64 'https://www.example.com/' --quiet --max-wait-for-load=30000 --output=html --output=json --output=csv --output-path=/home/chrome/reports/www_example_com --emulated-form-factor=desktop --throttling-method=provided
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/home/chrome/reports\") set in config.json failed: permission denied": unknown.
[jay:~] 126 $ sudo chmod o+wx tmp/
[jay:~] $ docker run --rm --name lighthouse -v "$PWD/tmp/:/home/chrome/reports" --cap-add=SYS_ADMIN femtopixel/google-lighthouse:4.0.0-alpha.0-amd64 'https://www.example.com/' --quiet --max-wait-for-load=30000 --output=html --output=json --output=csv --output-path=/home/chrome/reports/www_example_com --emulated-form-factor=desktop --throttling-method=provided
[jay:~] 12s $ #works
```
