### ISSUE TITLE
Running the image on CentOS7 results in "ChromeLauncher:error connect ECONNREFUSED 127.0.0.1"

### ISSUE THREAD

**Issue by hogarth-sv** [femtopixel/docker-google-lighthouse#8]
**Description**

When running the image on CentOS7/RHEL7 the result is a series of "waiting for browser" messages and eventually the ECONNREFUSED error.

See this from upstream: https://github.com/GoogleChrome/lighthouse/issues/2726
 
**Command line I used to start the container**
`docker run --rm --cap-add=SYS_ADMIN --name "localtest-15beb5d" -t -v "$(pwd)/lighthouse-reports/:/home/chrome/reports" "femtopixel/google-lighthouse:latest" "http://www.google.com"`

**Steps to reproduce the issue:**
1. Use a CentOS7 system, tested with upstream docker-ce
2. Run the command
3. Watch it fail

**Describe the results you received:**
```
  ChromeLauncher Waiting for browser................................................................................................. +501ms
  ChromeLauncher Waiting for browser................................................................................................... +502ms
  ChromeLauncher Waiting for browser..................................................................................................... +501ms
  ChromeLauncher Waiting for browser....................................................................................................... +501ms
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:43818 +1ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.yHe0vyL/chrome-err.log +1ms
  ChromeLauncher:error [0402/142744.311466:ERROR:zygote_host_impl_linux.cc(116)] No usable sandbox! If this is a Debian system, please install the chromium-sandbox package to solve this problem. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

**Describe the results you expected:**
```
  status Evaluating: Links have descriptive text +0ms
  status Evaluating: Page isn’t blocked from indexing +2ms
  status Evaluating: robots.txt is valid +2ms
  status Evaluating: Tap targets are sized appropriately +1ms
  status Evaluating: Document has a valid `hreflang` +2ms
  status Evaluating: Document avoids plugins +0ms
  status Evaluating: Document has a valid `rel=canonical` +1ms
  status Evaluating: Structured data is valid +0ms
  status Generating results... +0ms
  Printer html output written to /home/chrome/reports/www.google.com_2019-04-02_15-01-27.report.html +44ms
  CLI Protip: Run lighthouse with `--view` to immediately open the HTML report in your browser +0ms
  ChromeLauncher Killing Chrome instance 21 +0ms
```

**Additional information you deem important (e.g. issue happens only occasionally):**
By building on this image to add --no-sandbox to the chrome flags it works.

Perhaps the chrome flags could be made configurable by environment variable so that this is only overridden where required? Or can it be considered safe to --no-sandbox in this case seeing as it's confined in a docker container under an unprivileged user anyway (particularly if running with the seccomp profile instead of SYS_ADMIN caps).

**Comment by jaymoulin** [comment]
Thanks for the report and the tips ;)
